language: java
jdk:
  - oraclejdk8
before_install:
  # - sudo apt-get update
  # - sudo apt-get install --only-upgrade -y oracle-java8-installer
  # - pip install --user codecov
after_success:
  # - codecov
  # - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - "$HOME/.m2"
install:
  - mvn clean install -DskipITs=true

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)