version: '3.1'

services:

    mysql8:
        image: mysql:8.0.1
        ports:
               - 3306:3306
        environment:
#            MYSQL_ROOT_PASSWORD: my-secret-pwd
            MYSQL_RANDOM_ROOT_PASSWORD:  "yes"
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: example1db  

