version: '3.1'

services:

    mysql8:
        image: mysql:8.0.1
        ports:
               - 3306:3306
        environment:
            MYSQL_DATABASE: example1
            MYSQL_ROOT_PASSWORD: my-secret-pwd
            MYSQL_USER: mr_krabs
            MYSQL_PASSWORD: my-secret-pwd
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d


